/******************************************************************************
 * Copyright (C) 2026 JesMicro.
 *
 * SPDX-License-Identifier: MIT
 *
 * @file bsp_wt588f02b_8s.c
 *
 * @par dependencies
 * - bsp_wt588f02b_8s.h
 *
 * @author Jace | Development Dept. | JesMicro
 *
 * @brief Provides one-wire serial control for the WT588F02B-8S voice chip.
 *
 * Processing flow:
 *
 * wt588f_init() registers the DMA callback and waits for the voice chip to
 * complete power-on initialization. wt588f_list_play() starts TIM2 PWM and
 * sends the F3 command with voice addresses 0x00, 0x01, and 0x02. Each byte
 * is encoded into a compare buffer and transferred to TIM2 CCR1 by DMA. The
 * DMA callback releases the sender after each completed buffer.
 *
 * @version V1.0 2026-08-29
 *
 * @note 1 tab == 4 spaces!
 *
 ******************************************************************************/

#include "bsp_wt588f02b_8s.h"

/************************ Definitions ************************/

static volatile uint8_t s_tx_busy = 0U;

static void wt588f_dma_callback(DMA_HandleTypeDef* _hdma);


/**
 * @brief Initializes one-wire communication with the WT588F02B-8S.
 *
 * Registers the DMA transfer-complete callback, enables TIM2 update DMA
 * requests, and waits for the voice chip to complete power-on initialization.
 *
 * @return None.
 *
 * @note Call this function after MX_DMA_Init() and MX_TIM2_Init().
 */
void wt588f_init(void)
{
    /* Register the DMA transfer-complete callback. */
    if (HAL_OK !=
        HAL_DMA_RegisterCallback(htim2.hdma[TIM_DMA_ID_UPDATE],
                                 HAL_DMA_XFER_CPLT_CB_ID,
                                 wt588f_dma_callback))
    {
        Error_Handler();
    }

    /* Enable DMA requests generated by TIM2 update events. */
    __HAL_TIM_ENABLE_DMA(&htim2, TIM_DMA_UPDATE);

    /* Wait for the voice chip to complete power-on initialization. */
    HAL_Delay(200U);
}


/**
 * @brief Sends one control-command byte to the WT588F02B-8S.
 *
 * Builds the command waveform in a compare buffer and starts a DMA transfer
 * from the buffer to TIM2 CCR1. The command bits are transmitted LSB first.
 *
 * @param[in] command Control-command byte, such as 0xF3.
 *
 * @return None.
 *
 * @note TIM2 PWM must be running before this function is called.
 */
static void wt588f_send_command(uint8_t command)
{
    /*
     * Elements 0-5 generate the initial high level.
     * Elements 6-12 generate the 5.6 ms start-low level.
     * Elements 13-20 contain the eight command bits.
     * Elements 21-27 generate the command-end high level.
     */
    static uint32_t cmp_buffer[28] =
    {
        800U, 800U, 800U, 800U, 800U, 800U,
        0U,   0U,   0U,   0U,   0U,   0U,   0U,
        0U,   0U,   0U,   0U,   0U,   0U,   0U,   0U,
        800U, 800U, 800U, 800U, 800U, 800U, 800U
    };

    /* Encode the eight command bits into PWM compare values. */
    for (uint8_t index = 13U; index < 21U; ++index)
    {
        if (0U != (command & 0x01U))
        {
            cmp_buffer[index] = 600U;
        }
        else
        {
            cmp_buffer[index] = 200U;
        }

        command >>= 1U;
    }

    /* Start the update-triggered DMA transfer for the complete command. */
    s_tx_busy = 1U;

    if (HAL_OK !=
        HAL_DMA_Start_IT(htim2.hdma[TIM_DMA_ID_UPDATE],
                         (uint32_t)cmp_buffer,
                         (uint32_t)&htim2.Instance->CCR1,
                         (uint32_t)(sizeof(cmp_buffer) /
                                    sizeof(cmp_buffer[0]))))
    {
        s_tx_busy = 0U;
        Error_Handler();
    }
}


/**
 * @brief Sends one voice-address byte to the WT588F02B-8S.
 *
 * Builds the address waveform in a compare buffer and starts a DMA transfer
 * from the buffer to TIM2 CCR1. The address bits are transmitted LSB first.
 *
 * @param[in] address Voice address, such as 0x00, 0x01, or 0x02.
 *
 * @return None.
 *
 * @note Send the F3 command before calling this function.
 */
static void wt588f_send_address(uint8_t address)
{
    /*
     * Elements 0-6 generate the 5.6 ms start-low level.
     * Elements 7-14 contain the eight address bits.
     * Elements 15-22 generate the address-end high level.
     */
    static uint32_t cmp_buffer[23] =
    {
        0U,   0U,   0U,   0U,   0U,   0U,   0U,
        0U,   0U,   0U,   0U,   0U,   0U,   0U,   0U,
        800U, 800U, 800U, 800U, 800U, 800U, 800U, 800U
    };

    /* Encode the eight address bits into PWM compare values. */
    for (uint8_t index = 7U; index < 15U; ++index)
    {
        if (0U != (address & 0x01U))
        {
            cmp_buffer[index] = 600U;
        }
        else
        {
            cmp_buffer[index] = 200U;
        }

        address >>= 1U;
    }

    /* Start the update-triggered DMA transfer for the complete address. */
    s_tx_busy = 1U;

    if (HAL_OK !=
        HAL_DMA_Start_IT(htim2.hdma[TIM_DMA_ID_UPDATE],
                         (uint32_t)cmp_buffer,
                         (uint32_t)&htim2.Instance->CCR1,
                         (uint32_t)(sizeof(cmp_buffer) /
                                    sizeof(cmp_buffer[0]))))
    {
        s_tx_busy = 0U;
        Error_Handler();
    }
}


/**
 * @brief Sends a three-address continuous-play sequence.
 *
 * Starts TIM2 PWM, sends F3 with voice addresses 0x00, 0x01, and 0x02, and
 * stops TIM2 PWM after the final DMA transfer completes.
 *
 * @return None.
 *
 * @note The function waits for each DMA transfer to complete before starting
 *       the next command or address transfer.
 */
void wt588f_list_play(void)
{
    /* Start PWM once for the complete continuous-play sequence. */
    if (HAL_OK != HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1))
    {
        Error_Handler();
    }

    /* Send the continuous-play command and voice address 0x00. */
    wt588f_send_command(0xF3U);
    while (0U != s_tx_busy)
    {
    }

    wt588f_send_address(0x00U);
    while (0U != s_tx_busy)
    {
    }

    /* Send the continuous-play command and voice address 0x01. */
    wt588f_send_command(0xF3U);
    while (0U != s_tx_busy)
    {
    }

    wt588f_send_address(0x01U);
    while (0U != s_tx_busy)
    {
    }

    /* Send the continuous-play command and voice address 0x02. */
    wt588f_send_command(0xF3U);
    while (0U != s_tx_busy)
    {
    }

    wt588f_send_address(0x02U);
    while (0U != s_tx_busy)
    {
    }

    /* Stop PWM only after the complete continuous-play sequence. */
    if (HAL_OK != HAL_TIM_PWM_Stop(&htim2, TIM_CHANNEL_1))
    {
        Error_Handler();
    }
}


/**
 * @brief Handles completion of a WT588F02B-8S DMA transfer.
 *
 * Clears the transmission-busy flag after the configured compare buffer has
 * been transferred to TIM2 CCR1. TIM2 PWM remains running between bytes.
 *
 * @param[in] _hdma DMA handle supplied by the HAL callback mechanism.
 *
 * @return None.
 *
 * @note This function runs in DMA interrupt context.
 */
static void wt588f_dma_callback(DMA_HandleTypeDef* _hdma)
{
    if (_hdma == htim2.hdma[TIM_DMA_ID_UPDATE])
    {
        s_tx_busy = 0U;
    }
}
